### ISSUE TITLE
Represent Codes as Phrases?

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/escom-xml#1]
From EChA's Risk Management Implementation Unit via email, 26 October 2018:

> after some additional  reflections, we believe that the UseMapUseCode, SpercCode, SwedCode, ScedCode should be expressed as a phrase rather than a string. As we understand it, a “string” (up to 250 characters and no UUID assigned) will need to be typed in manually, this lends itself to errors, as opposed to a phrase which an IT tool can select from the Catalogue. The Code’s construction e.g. sector_SWED_8b(i_l_II)v, as such does not need translation, and a specific metadata could be assigned to such phrases (to distinguish them from phrases really contributing to inflation of the Catalogue). Nevertheless to limit the number of such phrases it could still be envisaged to express a version number as a separate phrase.

**Comment by dirk-qualisys** [comment]
My personal view: Phrases should be used whenever, but only if, the content needs translation. Free text might be error-prone and invite to abuse the field for other than the wanted data, so I think it is good to change the data type. But the best representation would be an enum - easy to validate, no misunderstandings, and no need to fill phrase catalogues with phrases that have the same text in all languages.

What do you think?

**Comment by Leo3E** [comment]
We had a brief internal discussion here and agree with Dirk's suggestion and his rationale.

**Comment by XMLeuropa2019** [comment]
Dirk/Leo, in your feedback on GitHub, you propose an “enum” as the solution, which we understand as being shorthand for an enumeration. Our understanding is that enumerations are always included (hardcoded) in the XSD itself. Thus it needs a new version of XSD each time a new code is added. An enumeration type is therefore useful in cases where there is a “closed” set of values that is mostly immutable, i.e. changes are infrequent. We anticipate that sectors will update their SPERCs, SWEDs etc. and develop new ones, so how would the enumeration work in practice to account for such additions?

**Comment by dirk-qualisys** [comment]
The three representations as phrase, string or enum(eration) vary in their properties:

1. phrase and string cannot be validated for proper content, but are thus flexible to extend without XSD modification
2. phrase and enumeration require new releases (of the phrase library or schema) for the addition of SPERCs etc., while string is free to cover any content unless it is restricted with a pattern or length constraint. Schema update releases are much easier in the new environment, so there might be sync'ed schema releases whenever necessary.

If a schema change is done just to extend an enum type and your software does not validate against the new schema, validation would fail. But if the change is so small, exchanging the schema does not create more effort that updating the phrase library (or even less). So as far as I can see, updating a system to cover new SPERCs etc. creates no effort with a string representation and some work (but no structural changes) with either phrase or enumeration.

Or is there a naming convention that allows us to define patterns so that we can use a restriction of string to make sure the content is valid?

**Comment by jrmiron** [comment]
Updating schema to often will make schema management difficult because at least for imports, you will have to be able to handle all versions.
For phrases catalogues, if the user did not initialise his software with all versions, it is not so important. At import time, the probability to have a missing phrase is low.
But we could imagine to have different catalogues. One for phrases that need translations, another one for SPERCs etc. ('technical phrases').
We could declare the used versions of catalogues in the XML header.

**Comment by dirk-qualisys** [comment]
At least for us, updating the phrase catalogue is much more effort than updating the schema. Let's assume the exporting system uses a newer version of phrases or schema than the importing system:

- If the deviation is in phrases, I might detect this by checking the phrase catalogue version declaration in XML, or I might overlook it. In both cases, the document would validate against the schema, but I could run into unknown phrases that need special treatment. If the version deviation is just an added SPERC and my import file does not use it, nothing happens (except that the phrase catalogue version might throw a warning).

- If the deviation is in the schema, I will surely detect this if I try to validate, or overlook it if I do not validate the incoming documents - which happens more often than I would have thought: Especially if the documents come from a trusted source, our customers never validate the documents. If the deviation is just an added SPERC, it is a good workaround to validate against the newest know schema which has a version number lower than the one received. If the added SPERC is not used, the document would validate against the older schema. But if you really validate, you would know where to find the proper schema.

So I think both solutions are more or less equivalent, and I would still prefer enumerations (or better: pattern restricted strings) over phrases. Setting up a second, not-to-be-translated phrase catalogue would need further discussion in the phrase group or steering committee.

What do the others prefer?

**Comment by dirk-qualisys** [comment]
Researching the current situation, I found GES titles which might compare to what we discuss. The have a translatable part (the title itself) and the non-translatable code, which is stored as a separate field, but in the phrase catalogue, such as "Concawe-CGES4_I". The same is true for "AISE SPERC  2.1.l.v2", which translates into "Formulation of liquid Detergents/ Maintenance Products: High Viscosity (small scale)". 

Do we all agree that the above discussion was about using the SPERC code in place of the translatable phrase text, i.e. as a separate phrase in addition to the SPERC title phrase we might want to have? I am certainly not against adding SPERC title phrases, but in this case we would take the SPERC code from the title phrases and should not have a separate field for it.

**Comment by Leo3E** [comment]
I think we discussed this before and decided to use codes and not phrases.

Thanks,
Leo

**Comment by markd-3e** [comment]
Regarding the XSD/Enum approach, I’m not necessarily opposed to it, but feel the library is more suitable because SPERCs always have corresponding phrase that needs to be translated.  I also feel the library is better suited to handle any volatility that may arise in the code’s naming convention.  

Considering the “AISE SPERC 2.1.l.v2” example that Dirk mentioned, I think it would be ideal to place both the translatable title and non-translatable code in the library.  However, I think the best way to express this code/text combo in the library is to place the translatable portion in the translatable text field, and then include the SPERC code in the “Original Phrase Code” field.  In fact, I believe this is how the AC, PC, and PROC phrase/code combos are currently expressed in the library, so, we have a precedent for this approach.

**Comment by dirk-qualisys** [comment]
Putting all the parts together, this is the status:

- @jrmiron and @markd-3e are in favor of maintaining the lists in the phrase library, not in the XSD.
- @Leo3E cited correctly that there is a decision to put only translatable text into phrases.

What seems like a contradiction can be resolved as follows: We put the text of SPERCs etc. in the phrase library and assign the codes as an "OriginalCode" to the same phrase. ESCom just cites the phrase number, with that phrase number, the SPERC (code) can be taken from the library. In other words: We won't have a field for the SPERC code only, but one phrase field that consistently represents one SPERC text and code per phrase (which is of course maintained in the phrase library). If there is no comment in the next days, I will post an implementation proposal after two days.

**Comment by markd-3e** [comment]
Thank you for the summary and resolution, Dirk.  

Sounds like a "best of both worlds" type of solution, I like it!

**Comment by Leo3E** [comment]
Thanks again, Dirk!  Mark’s position is what Verisk 3E is in favor of.  Hope we can collect all other opinions quickly for the May release.

**Comment by jrmiron** [comment]
Same for us. Thanks.

**Comment by dirk-qualisys** [comment]
I am sorry for the delay due to preparation of the [Workshop in Berlin](https://www.esdscom.eu/english/registration/). Actually the XSD implementation is quite simple:

`<xs:element minOccurs="0" name="SpercCode" type="ESCOMXML:String255">
` 

would be replaced with

`<xs:element minOccurs="0" name="Sperc" type="ESCOMXML:Phrase">
`

and the same is true for SWEDs and SCEDs. 

More important is that phrases are currently inconsistent, and I hope we can resolve this in a maintenance release either way. For the above approach, phrases like 11133170215 (Text "AISE SPERC 2.1.a.v1", no Original Code) should change to have the current text as their Original Code - just as the GES phrases like 11133171008 (Text "Use of the substance within laboratory settings within enclosed or contained systems, including incidental exposures during material transfers and equipment cleaning", Original Code "Concawe-CGES17_I").

It is necessary to have a common approach for (G)ES and SCED/SWED/SPERCs in the phrase catalogue as both have codes and translated names. With all the aspects discussed here, I think it is most consistent to use the Phrase type and modify the phrases to read the codes from the Masterfile column "Original Phrase Code" / the Chesar field <originalCode>.

**Comment by XMLeuropa2019** [comment]
Thank you for this proposal Dirk and our apologies for taking some time to reply. We are still analysing what this would mean from a Chesar perspective. We understand that it should not present too many difficulties when importing an ESCom XML file, but from the ESCom XML file creation perspective it seems it would be quite a challenge to implement a solution where 2 fields which are currently separated in the SPERC format would be referring to the same phrase ID in the catalogue. Besides that it would mean enabling the SPERC developer to search in another column than the phrase description, which is how the functionality currently works. We will come back to you once this analysis has been finalised. 
However, the proposed solution does not seem to have any impact the XSD and we therefore assume that this should not be a reason to delay the publication of the ESCom 2.1 XSD.

**Comment by dirk-qualisys** [comment]
Can you foresee how long your analysis might take? I think it is generally worth waiting for your results and decide afterwards, as the decision has impact on both XML and phrases. Plus if you cannot reasonably support that solution, the second best option (according to the majority opinion, as I understand it) would be some enumeration or string type, not phrases, requiring a maintenance release for 2.1 then.

**Comment by XMLeuropa2019** [comment]
After some further analysis and discussion, we have concluded on a way in which we could accommodate the proposal in Chesar. We therefore agree to go ahead with the proposed solution of having the SPERC (/SWED/SCED) title and code in the same phrase ID in the catalogue, with the code as the Original code and the title as the Phrase description. As Dirk noted, the main impact will indeed be that the phrase catalogue would need to be updated accordingly, to re-arrange the available information and also to make sure the right metadata is included (i.e. phrases related to SPERCs would need to have the metadata referring to the new field in the XSD). We will plan to implement the required change in Chesar 3.5, but this would only work if the new version of the catalogue is released before or together with the release of Chesar 3.5, which is planned for end of October.

**Comment by Leo3E** [comment]
Thanks!  I don’t see whom this message is coming from but I assume this is from ECHA (Andrew?).

Dirk,

It looks like we are cleared for the ESCOM 2.1 release.  This is great!  Will it be also possible for you to coordinate with the Phrase group to include the new phrases?

Thanks,
Leo

**Comment by dirk-qualisys** [comment]
Deleted Leo's comment as this was just an email reply to a GitHub notification and probably not intended for posting.
