### ISSUE TITLE
Small correction to “EffectivenessWaterlInPercent" ➦ “EffectivenessWaterInPercent"

### ISSUE THREAD

**Issue by jrmiron** [esdscom/escom-xml#2]
An extra "l" character is present in this element name. The element should be renamed.
The deprecated “EffectivenessWater**l**InPercent" can be keep for 1 release for compatibility and definitely removed in the next release.

**Comment by dirk-qualisys** [comment]
Thanks for pointing this out! As there is no date for a release after 2.1, I suggest we remove the wrong wording directly. Any objections?

**Comment by jrmiron** [comment]
Personally, it is OK for us.
