### ISSUE TITLE
ExposureScenarioStructuredShortTitle inappropriate

### ISSUE THREAD

**Issue by dirk-qualisys** [esdscom/escom-xml#3]
Several issures:

- The type ExposureScenarioStructuredShortTitle has a representation that included use descriptor codes which are not necessary for the ES, if I understand the schema documentation correctly. Instead they are meant for application if the same ES is communicated together with other ESs, so that the Structured Short Title would require a change for the purpose of differentiation. This is redundant, as the same use descriptors are part of the ES already.

- These codes are represented as phrases, which we are going to avoid according to issue #1.

- The life cycle stage as described in rule 1 of the Structure Short Title algorithm has no place in this type.

**Comment by dirk-qualisys** [comment]
New definition:
![grafik](https://user-images.githubusercontent.com/4411785/59524156-73968a00-8ed3-11e9-87cd-89f662e9f402.png)

**Comment by dirk-qualisys** [comment]
Received an email today:

> 
> To be honest, we are a bit puzzled by the changes made. If we understand correctly, you have made the following changes:
> 
> ·         A series of fields, which were used to specify PC/AC/SU codes, have now been removed from the SST
> 
> ·         In contrary, LifeCycleStage has been added to the SST
> 
>  
> 
> We understand that your reasoning for removing the fields for the codes is because this information can also been found elsewhere in the XSD. However the life cycle stage is also already included in another place in the XSD.
> 
> As far as we understand, according to the document on structured short titles, both the PC/AC/SU and life cycle stage are part of the SST. The PC/AC/SU codes are optional, however it is recommended to include the list of codes in brackets when there are several (in which case the SSTMarketInformationProductCategory only says “various products” which is of course not very informative). Of course it’s true that this information can also be retrieved from another place in the XSD, but this would mean multiple nodes would need to be checked and also that the consuming systems would need to re-implement the logic themselves. So it may be easier to keep these fields as they were.
> 
> Maybe we have misunderstood your intentions or the documents, would you mind explaining a bit further?

**Comment by dirk-qualisys** [comment]
I am sorry if I was not verbose enough regarding the changes. My assumptions were these:

- Any use category is in future represented by a phrase which has an OriginalCode entry for the code and a text for the wording, because that is what we discussed in issue #1 for consistency with the SpERCs, SWEDs, SCEDs.
- The Structured Short Title should follow the very same approach for consistency with the rest of EScom.
- Any redundancy should be avoided (in any data transmission / storage). So the SST part of EScom "repeats" parts of the use descriptors because it is the result of the SST algorithm, and the full lists of use descriptors are available in another part of ESCom as you mentioned. We still need to ensure that use descriptors which are part of the SST are indeed part of the full list.
- "LifeCycleStage"was, to my understanding, missing completely.

Rethinking the processes, I see your point regarding the collection of a PC/AC/SU list from other parts of the Exposure Scenario. If we do it that way, we also could not make sure that the list of codes printed in the SST is exactly what the author intended, because the SST algorithm recommends limiting the number of codes to 5, but leaves the dicision to the IT systems or users. Thank you for your valuable input!

Thus I will reintroduce fields for codes again - but according to the discussion for issue #1 as strings, not as phrases, because the code list is not meant to be translated and we will eliminate code-only phrases from the library. I hope that sounds reasonable and consistent for you.

**Comment by ECHA-Chesar** [comment]
Thanks for the additional explanation, indeed the re-addition of the PC/AC/SU codes seems to make sense. We wonder however whether it would be more consistent to leave them as phrases, just like in the other places in the Exposure Scenario. Is there a specific reason why they should be included differently in the SST than in the rest of the Exposure Scenario? Note that the phrases for PC/AC/SU in the phrase library are already built in the way which has now been agreed to introduce for SPERCs/SWEDs/SCEDs, i.e. they have the code as OriginalCode and the text for the wording. Therefore we assume that the same phrases could be re-used in the SST.

**Comment by dirk-qualisys** [comment]
Thanks for commenting. You are right that we could roll it back and reuse the current phrases, but as concluded in https://github.com/esdscom/escom-xml/issues/1#issuecomment-489569627 and the following comments, the decision was that phrases should be used (only) when there is a translatable part, and then the codes go into the OriginalCode field of the phrases. @jrmiron , @Leo3E and @markd-3e might correct me if I am wrong here.

Because in SSTs only the codes should be cited and this content is meant to build a human-readable title, I implemented them as strings now. The advantage of a phrase representation is that consistency checks between SST and use descriptors are easier, but with the current phrase type lacking a field for codes, I can't see how the SST could be printed from an ESCom file without the phrase catalogue and some heavy software logic behind, including some sources of error.

**Comment by ECHA-Chesar** [comment]
I see your point about the needing the ESCom phrase catalogue to be able to print the SST, but on the other hand the same is true for most of the ESCom file. There seem to be pros and cons for both approaches and as it is a minor issue we are fine with proceeding as suggested (i.e. use strings instead of phrases as codes).

The comment for requiring the phrase catalogue for generating the SST is true (indeed someone would have to use the catalogue to map the phrase to the code) but on the other hand (as you correctly pointed out) the same holds almost for everything in the XML transformation.
