### ISSUE TITLE
Version number 2.1 to be added to "ESComXMLVersionNumber" type in schema definition

### ISSUE THREAD

**Issue by ECHA-Chesar** [esdscom/escom-xml#5]
Thanks a lot for updating the header to include the version 2.1 instead of 2.0 (issue 4). We noticed that there is one more place where this change needs to be incorporated, in the definition of the type "ESComXMLVersionNumber". Currently this type is restricted to the value 2.0. We assume that it should also contain 2.1 (in addition to or instead of 2.0, as we understand both solutions will work and it is a matter of preference whether you want to keep the historical reference). The piece of code which is referred to is copied below.

<xs:simpleType name="ESComXMLVersionNumber">
		<xs:annotation>
			<xs:documentation>
				Specifies the ESComXML version number for which the XML
				file is valid.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="2.0" />
		</xs:restriction>
	</xs:simpleType>

**Comment by dirk-qualisys** [comment]
Thank you for pointing this out!
Because the changes from 2.0 to 2.1 are not backwards compatible (e.g. type changes from Phrase to string255) we should not include 2.0 in the enumeration, so I will replace it.
